
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 10 15:46:49 CST 2013
//----------------------------------------------------

package Analisis_Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TAsig = 42;
  public static final int TTrue = 23;
  public static final int TLength = 22;
  public static final int TDecimales = 46;
  public static final int TComa = 27;
  public static final int TVoid = 4;
  public static final int TCorDer = 13;
  public static final int TResta = 31;
  public static final int TLlaveDer = 8;
  public static final int TPrintln = 21;
  public static final int TDivision = 33;
  public static final int TElse = 44;
  public static final int TNew = 26;
  public static final int TRead = 56;
  public static final int TImplements = 53;
  public static final int TParIzq = 11;
  public static final int TIn = 55;
  public static final int TIgual = 35;
  public static final int TStatic = 49;
  public static final int TIf = 43;
  public static final int TClass = 2;
  public static final int TMenorIgual = 39;
  public static final int TPyComa = 28;
  public static final int TBoolean = 17;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int TMayorIgual = 37;
  public static final int TStringLiteral = 60;
  public static final int TStringConst = 59;
  public static final int TMenor = 38;
  public static final int TSystem = 19;
  public static final int TReturn = 15;
  public static final int TDiferente = 34;
  public static final int TMult = 32;
  public static final int TChar = 51;
  public static final int TError = 47;
  public static final int TY = 41;
  public static final int TPuntoAst = 57;
  public static final int TMayor = 36;
  public static final int TParDer = 12;
  public static final int TPunto = 29;
  public static final int TID = 7;
  public static final int TImport = 52;
  public static final int TCorIzq = 14;
  public static final int TO = 40;
  public static final int TLlaveIzq = 9;
  public static final int TWhile = 18;
  public static final int TIntegerLiteral = 58;
  public static final int TFloat = 50;
  public static final int TExtends = 10;
  public static final int TNegacion = 45;
  public static final int TPublic = 3;
  public static final int TInt = 16;
  public static final int TFalse = 24;
  public static final int TOut = 20;
  public static final int TSuma = 30;
  public static final int TString = 6;
  public static final int TExit = 54;
  public static final int TMain = 5;
  public static final int TEOF = 48;
  public static final int TThis = 25;
}

